Sprint4
denistakeda/alerting pull request #11
Opened 2023-02-09 15:31 UTC by denistakeda

2023-02-13 07:54 UTC, Barugoo commented on cmd/agent/main.go
> +
Согласно заданию, сбор этих метрик у нас должен идти в **_отдельной_** горутине

2023-02-13 07:56 UTC, Barugoo commented on cmd/agent/main.go
> +	for i := 0; i < rateLimit; i++ {
Кажется, что сделав воркерпул здесь нам ничего не мешает нафигачить запросов из другой части приложения. Я предлагаю сделать воркер-пул на уровне HTTP-клиента, чтобы **_все_** хттп-запросы которые делаются в агенте обязательно шли через него. Вот как идея:
https://codereview.stackexchange.com/questions/268404/golang-http-client-wrapper-with-rate-and-concurrency-limiting

2023-02-13 07:57 UTC, Barugoo requested changes
Хорошо, но есть замечания

2023-02-14 06:31 UTC, denistakeda commented on cmd/agent/main.go
> +	for i := 0; i < rateLimit; i++ {
Поправил

2023-02-14 06:32 UTC, denistakeda commented on cmd/agent/main.go
> +
Поправил

2023-02-14 21:51 UTC, Barugoo commented on internal/httpclient/httpclient.go
> +func sendRequest(bus <-chan *task, client *http.Client) {
минорный коммент - я бы лучше назвал такую функцию `handleRequests` чтобы из названия было понятно, что она не один раз отправляет запрос, а непрерывно хэндлит какие-то задачи

2023-02-14 21:53 UTC, Barugoo approved these changes
Отлично! работу принимаю

2023-02-15 06:47 UTC, merged